"""
CR-001C-C V1 — Coupon test fixture seeder (Addendum A.1).

Idempotent — re-running is safe. Scoped to a single CRM user.
Cleanup deletes only the `QA_C1_*` fixtures.

Usage (CLI):
    python -m backend.tests.seed_coupon_v1_fixtures seed --user-id <USER_ID> [--customer-id <CID>]
    python -m backend.tests.seed_coupon_v1_fixtures cleanup --user-id <USER_ID>

Or programmatically from QA:
    from backend.tests.seed_coupon_v1_fixtures import seed, cleanup
    fixture = await seed(db, user_id, customer_id=...)
    ...
    await cleanup(db, user_id)
"""
from __future__ import annotations

import asyncio
import argparse
import sys
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional


FIXTURE_PREFIX = "QA_C1_"


def _make_iso(offset_days: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(days=offset_days)).isoformat()


def _build_fixtures(user_id: str, vip_customer_id: Optional[str]) -> list[dict]:
    now_iso = datetime.now(timezone.utc).isoformat()
    return [
        {
            "code": f"{FIXTURE_PREFIX}FLAT50",
            "discount_type": "flat",
            "discount_value": 50.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 200.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in"],
            "description": "QA flat ₹50 off",
            "title": "QA Flat 50",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": True,
        },
        {
            "code": f"{FIXTURE_PREFIX}PCT10",
            "discount_type": "percentage",
            "discount_value": 10.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 100.0,
            "max_discount": 80.0,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA 10% off, cap ₹80",
            "title": "QA 10% Off",
            "coupon_type": "order",
            "stackable_with_loyalty": True,
            "is_active": True,
        },
        {
            "code": f"{FIXTURE_PREFIX}EXPIRED",
            "discount_type": "flat",
            "discount_value": 25.0,
            "start_date": _make_iso(-10),
            "end_date": _make_iso(-1),  # expired yesterday
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos"],
            "description": "QA expired coupon",
            "title": "QA Expired",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": True,
        },
        {
            "code": f"{FIXTURE_PREFIX}INACTIVE",
            "discount_type": "flat",
            "discount_value": 25.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos"],
            "description": "QA inactive coupon",
            "title": "QA Inactive",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": False,
        },
        {
            "code": f"{FIXTURE_PREFIX}PERUSER",
            "discount_type": "flat",
            "discount_value": 10.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 1,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos"],
            "description": "QA per-user 1 limit",
            "title": "QA Per-User",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": True,
        },
        {
            "code": f"{FIXTURE_PREFIX}VIPONLY",
            "discount_type": "flat",
            "discount_value": 100.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 500.0,
            "max_discount": None,
            "specific_users": [vip_customer_id] if vip_customer_id else [],
            "applicable_channels": ["pos", "dine_in"],
            "description": "QA VIP-only coupon",
            "title": "QA VIP Only",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": True,
        },
        # CR-001C-C V2 fixtures.
        {
            "code": "QA_C2_ITEMFLAT",
            "discount_type": "flat",
            "discount_value": 50.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in"],
            "description": "QA item flat ₹50 off coffee/tea food_ids",
            "title": "QA Item Flat 50",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "discount_scope": "item",
            "eligible_food_ids": ["182039", "182040"],
        },
        {
            "code": "QA_C2_ITEMPCT",
            "discount_type": "percentage",
            "discount_value": 20.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": 50.0,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA item 20% off coffee item_id, cap 50",
            "title": "QA Item 20% Off",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "discount_scope": "item",
            "eligible_item_ids": ["L_3324", "L_3325"],
            "max_applicable_qty": 2,
        },
        {
            "code": "QA_C2_CATFLAT",
            "discount_type": "flat",
            "discount_value": 100.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in"],
            "description": "QA category flat ₹100 off Beverages",
            "title": "QA Category Flat 100",
            "coupon_type": "category",
            "stackable_with_loyalty": False,
            "is_active": True,
            "discount_scope": "category",
            "eligible_category_ids": ["12"],
            "eligible_category_names": ["Beverages"],
        },
        {
            "code": "QA_C2_CATPCT",
            "discount_type": "percentage",
            "discount_value": 25.0,
            "start_date": _make_iso(-1),
            "end_date": _make_iso(30),
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": 200.0,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in"],
            "description": "QA category 25% off Beverages, cap 200",
            "title": "QA Category 25% Off",
            "coupon_type": "category",
            "stackable_with_loyalty": False,
            "is_active": True,
            "discount_scope": "category",
            "eligible_category_names": ["Beverages"],
        },
        # CR-001C-C V3-A fixtures — happy-hour / time-window.
        # Wide validity window so test-frozen clocks don't fail V1 start_date / end_date.
        {
            "code": "QA_C3A_HAPPYHOUR_V1",
            "discount_type": "percentage",
            "discount_value": 20.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": 200.0,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA V1 order-percentage happy-hour Mon-Fri 15:00-18:00 Asia/Kolkata",
            "title": "QA Happy Hour V1",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "simple",
            "valid_days": [0, 1, 2, 3, 4],
            "start_time": "15:00",
            "end_time": "18:00",
            "timezone": "Asia/Kolkata",
        },
        {
            "code": "QA_C3A_HAPPYHOUR_V2_ITEM",
            "discount_type": "percentage",
            "discount_value": 20.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": 50.0,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA V2 item-percentage happy-hour beverages Mon-Fri 15:00-18:00",
            "title": "QA Happy Hour V2 Item",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "discount_scope": "item",
            "eligible_food_ids": ["182039", "182040"],
            "max_applicable_qty": 2,
            "offer_type": "simple",
            "valid_days": [0, 1, 2, 3, 4],
            "start_time": "15:00",
            "end_time": "18:00",
            "timezone": "Asia/Kolkata",
        },
        {
            "code": "QA_C3A_OVERNIGHT",
            "discount_type": "flat",
            "discount_value": 50.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA overnight wrap 22:00-02:00 Fri only Asia/Kolkata",
            "title": "QA Overnight",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "simple",
            "valid_days": [4],
            "start_time": "22:00",
            "end_time": "02:00",
            "timezone": "Asia/Kolkata",
        },
        {
            "code": "QA_C3A_NOWINDOW",
            "discount_type": "flat",
            "discount_value": 30.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA no-window control (V3-A regression)",
            "title": "QA No Window",
            "coupon_type": "order",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "simple",
        },
        # CR-001C-C V3-B fixtures — BOGO / Buy-X-Get-Y.
        # Wide validity dates so frozen-clock V3-B tests don't trip V1 start/end.
        # discount_type is a non-consulted placeholder for V3-B (V1 normalizer is
        # skipped when offer_type ∈ {bogo, bxg}); we still set "flat" so the
        # field passes downstream consumers that read it.
        {
            "code": "QA_C3B_BOGO_COFFEE",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BOGO buy-1-get-1 coffee free (same-item)",
            "title": "QA BOGO Coffee",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bogo",
            "same_item_required": True,
            "buy_quantity": 1,
            "get_quantity": 1,
            "buy_food_ids": ["182039"],  # coffee
            "get_discount_type": "free",
            "allow_repeat": True,
            "pos_instruction": "Add a 2nd coffee to qualify for BOGO.",
        },
        {
            "code": "QA_C3B_BXG_BUY2GET1_SAME",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG buy-2-get-1 burger same-item free",
            "title": "QA BXG Buy-2-Get-1 Burger",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bxg",
            "same_item_required": True,
            "buy_quantity": 2,
            "get_quantity": 1,
            "buy_food_ids": ["B_001"],  # burger
            "get_discount_type": "free",
            "allow_repeat": True,
        },
        {
            "code": "QA_C3B_BXG_PIZZA_GARLIC_FREE",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG buy 2 pizza, get 1 garlic bread free",
            "title": "QA BXG Pizza+Garlic Free",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bxg",
            "same_item_required": False,
            "buy_quantity": 2,
            "get_quantity": 1,
            "buy_food_ids": ["P_001"],
            "get_food_ids": ["G_001"],
            "get_discount_type": "free",
            "allow_repeat": True,
        },
        {
            "code": "QA_C3B_BXG_PIZZA_GARLIC_PCT",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG buy 2 pizza, get 1 garlic bread 50% off",
            "title": "QA BXG Pizza+Garlic 50%",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bxg",
            "same_item_required": False,
            "buy_quantity": 2,
            "get_quantity": 1,
            "buy_food_ids": ["P_001"],
            "get_food_ids": ["G_001"],
            "get_discount_type": "percentage",
            "get_discount_value": 50.0,
            "allow_repeat": True,
        },
        {
            "code": "QA_C3B_BXG_PIZZA_GARLIC_FLAT",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG buy 2 pizza, get 1 garlic bread flat ₹150 off (cap by unit_price)",
            "title": "QA BXG Pizza+Garlic Flat",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bxg",
            "same_item_required": False,
            "buy_quantity": 2,
            "get_quantity": 1,
            "buy_food_ids": ["P_001"],
            "get_food_ids": ["G_001"],
            "get_discount_type": "flat",
            "get_discount_value": 150.0,  # > garlic unit_price 100 → cap
            "allow_repeat": True,
        },
        {
            "code": "QA_C3B_BXG_MAX_APPS",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG buy-1-get-1 same-item, max_applications=2",
            "title": "QA BXG max-apps",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bogo",
            "same_item_required": True,
            "buy_quantity": 1,
            "get_quantity": 1,
            "buy_food_ids": ["182039"],
            "get_discount_type": "free",
            "allow_repeat": True,
            "max_applications": 2,
        },
        {
            "code": "QA_C3B_BXG_NOREPEAT",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG buy-1-get-1 same-item, allow_repeat=False",
            "title": "QA BXG no-repeat",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bogo",
            "same_item_required": True,
            "buy_quantity": 1,
            "get_quantity": 1,
            "buy_food_ids": ["182039"],
            "get_discount_type": "free",
            "allow_repeat": False,
        },
        {
            "code": "QA_C3B_BXG_HIGHEST",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG same-item with apply_to_highest_item=True",
            "title": "QA BXG highest",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bogo",
            "same_item_required": True,
            "buy_quantity": 1,
            "get_quantity": 1,
            "buy_food_ids": ["P_001"],
            "get_discount_type": "free",
            "allow_repeat": True,
            "apply_to_highest_item": True,
        },
        {
            "code": "QA_C3B_BOGO_HAPPYHOUR",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BOGO + happy-hour Mon-Fri 15:00-18:00 IST",
            "title": "QA BOGO Happy Hour",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bogo",
            "same_item_required": True,
            "buy_quantity": 1,
            "get_quantity": 1,
            "buy_food_ids": ["182039"],
            "get_discount_type": "free",
            "allow_repeat": True,
            "valid_days": [0, 1, 2, 3, 4],
            "start_time": "15:00",
            "end_time": "18:00",
            "timezone": "Asia/Kolkata",
        },
        {
            "code": "QA_C3B_BXG_MAX_DISCOUNT",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": 75.0,  # ceiling regardless of free units
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG with coupon-level max_discount ceiling",
            "title": "QA BXG max-discount",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bogo",
            "same_item_required": True,
            "buy_quantity": 1,
            "get_quantity": 1,
            "buy_food_ids": ["P_001"],
            "get_discount_type": "free",
            "allow_repeat": True,
        },
        {
            "code": "QA_C3B_BXG_STACK_LOY",
            "discount_type": "flat",
            "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None,
            "per_user_limit": 5,
            "min_order_value": 0.0,
            "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA BXG same-item, stackable_with_loyalty=False (regression)",
            "title": "QA BXG Stacking",
            "coupon_type": "item",
            "stackable_with_loyalty": False,
            "is_active": True,
            "offer_type": "bogo",
            "same_item_required": True,
            "buy_quantity": 1,
            "get_quantity": 1,
            "buy_food_ids": ["182039"],
            "get_discount_type": "free",
            "allow_repeat": True,
        },
        # CR-001C-C V3-C fixtures — Every-Nth item.
        # discount_type=flat is a non-consulted placeholder (V1 normalizer is
        # skipped when offer_type is V3-C); the V3-C engine uses
        # nth_discount_type / nth_discount_value.
        {
            "code": "QA_C3C_NTH5_COFFEE_FREE",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 5th coffee free (same-item)",
            "title": "QA Every 5th Coffee", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 5,
            "nth_discount_type": "free",
            "eligible_food_ids": ["182039"],
            "allow_repeat": True,
            "pos_instruction": "Add more coffee to qualify for every 5th free.",
        },
        {
            "code": "QA_C3C_NTH3_DESSERT_PCT",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 3rd dessert 50% off",
            "title": "QA Every 3rd Dessert 50%", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 3,
            "nth_discount_type": "percentage",
            "nth_discount_value": 50.0,
            "eligible_food_ids": ["D_001"],
            "allow_repeat": True,
        },
        {
            "code": "QA_C3C_NTH4_BEV_FLAT",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 4th beverage ₹150 flat (cap by unit_price)",
            "title": "QA Every 4th Beverage Flat", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 4,
            "nth_discount_type": "flat",
            "nth_discount_value": 150.0,  # > unit_price 100 → cap
            "eligible_food_ids": ["B_BEV"],
            "allow_repeat": True,
        },
        {
            "code": "QA_C3C_NTH5_BEV_CAT_FREE",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 5th beverage (category) free",
            "title": "QA Every 5th Beverage Cat", "coupon_type": "category",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 5,
            "nth_discount_type": "free",
            "eligible_category_names": ["beverages"],
            "allow_repeat": True,
        },
        {
            "code": "QA_C3C_NTH5_EXCLUDED",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 5th beverage with excluded item",
            "title": "QA Every 5th Beverage Excluded", "coupon_type": "category",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 5,
            "nth_discount_type": "free",
            "eligible_category_names": ["beverages"],
            "excluded_item_ids": ["B_TEA"],
            "allow_repeat": True,
        },
        {
            "code": "QA_C3C_NTH5_MAX_APPS",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 5th coffee free with max_applications=2",
            "title": "QA Every 5th max-apps", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 5,
            "nth_discount_type": "free",
            "eligible_food_ids": ["182039"],
            "allow_repeat": True,
            "max_applications": 2,
        },
        {
            "code": "QA_C3C_NTH5_NOREPEAT",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 5th coffee free with allow_repeat=False",
            "title": "QA Every 5th no-repeat", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 5,
            "nth_discount_type": "free",
            "eligible_food_ids": ["182039"],
            "allow_repeat": False,
        },
        {
            "code": "QA_C3C_NTH3_HIGHEST",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 3rd dessert free with apply_to_highest_item=True",
            "title": "QA Every 3rd highest", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 3,
            "nth_discount_type": "free",
            "eligible_food_ids": ["D_001"],
            "allow_repeat": True,
            "apply_to_highest_item": True,
        },
        {
            "code": "QA_C3C_NTH5_HAPPYHOUR",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 5th coffee free + happy-hour Mon-Fri 15:00-18:00 IST",
            "title": "QA Every 5th Happy Hour", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 5,
            "nth_discount_type": "free",
            "eligible_food_ids": ["182039"],
            "allow_repeat": True,
            "valid_days": [0, 1, 2, 3, 4],
            "start_time": "15:00",
            "end_time": "18:00",
            "timezone": "Asia/Kolkata",
        },
        {
            "code": "QA_C3C_NTH5_STACK_LOY",
            "discount_type": "flat", "discount_value": 0.0,
            "start_date": "2020-01-01T00:00:00+00:00",
            "end_date": "2099-01-01T00:00:00+00:00",
            "usage_limit": None, "per_user_limit": 5,
            "min_order_value": 0.0, "max_discount": None,
            "specific_users": None,
            "applicable_channels": ["pos", "dine_in", "takeaway", "delivery"],
            "description": "QA every 5th coffee free, stackable_with_loyalty=False",
            "title": "QA Every 5th Stacking", "coupon_type": "item",
            "stackable_with_loyalty": False, "is_active": True,
            "offer_type": "nth_item",
            "nth_item_number": 5,
            "nth_discount_type": "free",
            "eligible_food_ids": ["182039"],
            "allow_repeat": True,
        },
    ]


async def seed(db, user_id: str, customer_id: Optional[str] = None) -> dict:
    """Idempotent seeding. Returns dict of {code: coupon_id}. Inserts only missing rows."""
    fixtures = _build_fixtures(user_id, customer_id)
    inserted: dict[str, str] = {}
    skipped: list[str] = []
    now_iso = datetime.now(timezone.utc).isoformat()
    for fx in fixtures:
        existing = await db.coupons.find_one(
            {"user_id": user_id, "code": fx["code"]}, {"_id": 0, "id": 1}
        )
        if existing:
            skipped.append(fx["code"])
            inserted[fx["code"]] = existing["id"]
            continue
        coupon_id = str(uuid.uuid4())
        doc = {
            "id": coupon_id,
            "user_id": user_id,
            **fx,
            "total_used": 0,
            "created_at": now_iso,
        }
        await db.coupons.insert_one(doc)
        inserted[fx["code"]] = coupon_id

    return {
        "user_id": user_id,
        "vip_customer_id": customer_id,
        "coupons": inserted,
        "skipped": skipped,
    }


async def cleanup(db, user_id: str) -> dict:
    """Delete only QA_C1_* and QA_C2_* fixtures and their child coupon_usage rows."""
    code_filter = {"$regex": f"^(?:{FIXTURE_PREFIX}|QA_C2_|QA_C3A_|QA_C3B_|QA_C3C_)"}
    coupons_to_remove = await db.coupons.find(
        {"user_id": user_id, "code": code_filter},
        {"_id": 0, "id": 1, "code": 1},
    ).to_list(50)
    ids = [c["id"] for c in coupons_to_remove]
    usage_deleted = 0
    if ids:
        res_usage = await db.coupon_usage.delete_many(
            {"user_id": user_id, "coupon_id": {"$in": ids}}
        )
        usage_deleted = res_usage.deleted_count
        # Also clean any legacy rows (no user_id) by coupon_id.
        res_usage_legacy = await db.coupon_usage.delete_many(
            {"coupon_id": {"$in": ids}, "user_id": {"$exists": False}}
        )
        usage_deleted += res_usage_legacy.deleted_count
    res_coupons = await db.coupons.delete_many(
        {"user_id": user_id, "code": code_filter}
    )
    return {
        "coupons_deleted": res_coupons.deleted_count,
        "coupon_usage_deleted": usage_deleted,
        "removed_codes": [c["code"] for c in coupons_to_remove],
    }


def _cli():
    parser = argparse.ArgumentParser(description="CR-001C-C V1 coupon fixture seeder")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_seed = sub.add_parser("seed")
    p_seed.add_argument("--user-id", required=True)
    p_seed.add_argument("--customer-id", default=None)
    p_cleanup = sub.add_parser("cleanup")
    p_cleanup.add_argument("--user-id", required=True)
    args = parser.parse_args()

    # Import here so CLI doesn't pull motor in test contexts that don't need it.
    sys.path.insert(0, "/app/backend")
    from core.database import db

    async def run():
        if args.cmd == "seed":
            res = await seed(db, args.user_id, args.customer_id)
        else:
            res = await cleanup(db, args.user_id)
        print(res)

    asyncio.run(run())


if __name__ == "__main__":
    _cli()
